bundle_root: "/cfs/klemming/home/s/simben/Private/MONAI_Bundles/Detection/RetinaNet"
preprocess_dir: "/mnt/Data/naiss2023-22-687/Data/2024-05-10_Autopet_v1.1/preprocess"
train_workers: 8
train_cache_num: 8
val_workers: 4
batch_size: 8
num_train_batches_per_epoch:  16
num_val_batches_per_epoch: 12
max_num_epochs: 836

ckpt_dir: "/cfs/klemming/home/s/simben/Private/MONAI_Bundles/Detection/RetinaNet/RetinaNet_Deep_models_2x1_Lightning"
warmup_ckpt_dir: "/cfs/klemming/home/s/simben/Private/MONAI_Bundles/Detection/RetinaNet/RetinaNet_Deep_models_2x1_WarmUp_Lightning"